language: android
android:
  components:
  - android-28
  - build-tools-28.0.3
before_install:
- openssl aes-256-cbc -K $encrypted_9cdd26030056_key -iv $encrypted_9cdd26030056_iv
  -in keystoreCalidad.jks.enc -out keystoreCalidad.jks -d
- cd SpaceInvaders
- chmod +x gradlew
- "./gradlew dependencies || true"
script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
deploy:
  provider: releases
  skip_cleanup: true
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file: spaceInvaders.apk
  on:
    repo: krate95/Calidad
    tags: true
    all_branches: true
before_deploy:
- cp $TRAVIS_BUILD_DIR/.keystore $HOME
- cd app/build/outputs/apk/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore.jks
  -storepass $storepass -keypass $keypass app-release-unsigned.apk spaceInvaders_keystore
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk spaceInvaders.apk"
env:
  global:
    secure: QtbqglE8OQwmr2U+KOYqkgT1MMfEaiNic5FI5fTEXwvU58uhOeWVOjv3w4czxile1vjWLizgViTviynd3fUqoLYOjxpZFWCxUkRtWmUlOPca5EVMIbeFL+c56REFQ+de8F5ETumw5AHG3WWbCccwIBocj7YrkmV6lcHumzsTTL0lnP3M2MCdNcGYHL5q4MyR58kZ7I0wuihaKx/ReENrv8jqpY47QVHLwcpynXEDCZrmKP2bAUTD0oFEgXD2s+6PH9tcmDbN99bcy3o5QKP4jL5qWJ6iFfKr2HnjOgvLTp26yHSmR1fSXgkJ9utDtLod2ZkhgY1UD5KSCjAwjGo8rAMwWa4NhNmApOvRZeX9OATA01lFvOR6w5YLKcO7Ul4o6LcJuKsJXXMyqUUqJNxLZ+dYSCdkHfUF0+1IXGE3ZG0Z1pz3GQjUtJa1/K+/2UUf/Uarev1So3LkNdhTFZIbX23hMB6smYgsAYnDFjmdWE+X36vrKaws0BIdgW3/3MWrwBNyZ+TlcgcyNsl7evvCWbEHS/SVyzmxibM1ApkaueOYGIlYCOUFaywdVIorYD7iw1RjF/Dg8BKSFeSlfyILgKyNQuWuZKvYpcWLF3+NWXRWsJP+a/ovzreMWw1XsIxotmv0sKOZohUZX15rMkxgtdEfvQ7JYzalx8LwocIb/6E=
