language: android
android:
  components:
    - android-28
    - build-tools-28.0.3
before_install:
  - cd SpaceInvaders
  - chmod +x gradlew
after_success:
  - ./upload-apk.sh 
script:
  - ./gradlew build
