language: android
android:
  components:
  - android-28
  - build-tools-28.0.3
before_install:
- openssl aes-256-cbc -K $encrypted_ca2a019b0943_key -iv $encrypted_ca2a019b0943_iv
  -in keystoreCalidad.jks.enc -out keystoreCalidad.jks -d
- cd SpaceInvaders
- chmod +x gradlew
- "./gradlew dependencies || true"
script:
- "./gradlew clean build -PdisablePreDex --stacktrace"
deploy:
  provider: releases
  skip_cleanup: true
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file: spaceInvaders.apk
  on:
    repo: krate95/Calidad
    tags: true
    all_branches: true
before_deploy:
- cp $TRAVIS_BUILD_DIR/keystoreCalidad.jks $HOME
- cd app/build/outputs/apk/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore.jks
  -storepass $storepass -keypass $keypass app-release-unsigned.apk spaceInvaders_keystore
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk spaceInvaders.apk"
env:
  global:
    secure: iRGGlqEj6rAVftJ5SEfSVgcXh8RSNTWUTCPP4SwVO3CBFV49aSj7hwu4WSN2P835XnNrDzP7kW6a7sRmgZbRIgdYKPEHsd6z9mMpv7aezKEaRsGgv4kIYVXamRwggMQdNhFWMpptBETrDVdylTsqf8cbogCrmOQhO/hPnCkY4TS0W/XEkXP47+vrcQw9nc6FRknaMjtJSW5WmokuYMmyvqw0eN24EOSfyxpVmDdVwsVE8S5YukV7RfKMQlqqlhtORBpW5XrRc/vF10SYO7gHJhfBH5aAA6k0Sh1tkgfyoCSVcyCMFRUgkaAhnEVlfK28X/nQHKLsPyTciVUdQZME3V42vN6W9Ueo4Sjp1IHlF5/1/AN90vJpHfZVpYjn/uSnVNwZ9jorth9vxdWk46yf2h24/fORljMTXbhAKG7Eg+xIGEW+9/ioiKiUoXZ6pwb6lpncotbDTxnIZDeTs+sMtEQH7JXWPE4diSkcHDymBcvNFCYmlff+OtcU2UFZ9kKfeG7ExEVCJANuwgLakwvvDohcNby9InnBbUPmHD4W1LZzulSlST0u7z81l/uBO6BImk+o/ppAB0ZnQ0ZkosH9An/bqJK9FrssY4VuqRVwftwb+cJ7J6sNy/Rc4TlFO9XpubOPf79R9F6ydd0h9RYD9hWZzj3btCxCAKz1LIG9Z6k=
