language: android
android:
  components:
  - android-28
  - build-tools-28.0.3
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_9cdd26030056_key -iv $encrypted_9cdd26030056_iv
  -in keystoreCalidad.jks.enc -out keystoreCalidad.jks -d
- cd SpaceInvaders
- chmod +x gradlew
- "./gradlew dependencies || true"
script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
deploy:
  provider: releases
  skip_cleanup: true
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file: spaceInvaders.apk
  on:
    repo: krate95/Calidad
    tags: true
    all_branches: true
before_deploy:
  - cp $TRAVIS_BUILD_DIR/.keystore $HOME
  - cd app/build/outputs/apk/
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk spaceInvaders_keystore
  # Verification
  - jarsigner -verify app-release-unsigned.apk
  - "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk spaceInvaders.apk"
env:
  global:
    secure: V8psknKxdYrx9k/5z//vtq1znUEHIhqnSsWX0D2pSZuxTlKpZwmx6hd6K65UExlu/2YaKbLD7ctKsSONVak7UQQ9SA5zBfluBmpsVxfu35f8ylABo/pDkjmoPexx15bCmiG+k/838p1L+fF87ZN9oWPkA4v2J+P1RdBeNRd8is8I7MkwwEnvNqsSFwjHyLbqiYkb+0bMw+nxeCjDmfvno76X1RlULyHch/eir0D64gNy/pZLsbeNS9FA3cDIu3Cm/G8pHyySI01lejlPfr1s4mY9QePklQLen3Rqf2wrA6e+7ZwMNm3hXN/4piMmkkzIA7aV8YUvrPJSxRLkUgF+T7aMwo1Ail2D8zqiRTcQvi0Nbb7BU9bRFCr4m70ILqhEejyv/l4z7QNy4HzRTskrrlgENTtCnFD0O0IBNdB4J76+5VfwkSBBXHklYhmPX53Khqv99BL5MsFMzrO/1nReEfbCDKmmIwKar20MgVz0PP0EmFpLzdRMiq/yzK0XFatINbR/GXyxt72miV8XVQ/6Q+Ogdr8U7xDAbGPWXpfQOYaA3o8yT35YxkvKqFpGtDobmeqGWn6QwH/oEwpEXDGdyrF/RG05V3wbO4V6EH/nWaEtiOgPOPJykPgHxxZ/eaOj0ebTMZw7N+m9UNLNbAn7IkJcNKUlbOjpI75QME0Dr+s=
