language: android
android:
  components:
  - android-28
  - build-tools-28.0.3
addons:
  sonarcloud:
    organization: "krate95-github"
    token: "$SONAR_TOKEN"
before_install:
  - openssl aes-256-cbc -K $encrypted_ca2a019b0943_key -iv $encrypted_ca2a019b0943_iv
    -in keystoreCalidad.jks.enc -out keystoreCalidad.jks -d
  - cd SpaceInvaders
  - chmod +x gradlew
  - "./gradlew dependencies || true"
script:
  - "./gradlew clean build -PdisablePreDex --stacktrace"
  - sonar-scanner
before_deploy:
  mv /home/travis/build/krate95/Calidad/SpaceInvaders/app/build/outputs/apk/release/app-release.apk /home/travis/build/krate95/Calidad/SpaceInvaders/app/build/outputs/apk/release/spaceInvadersG6.apk

deploy:
  provider: releases
  skip_cleanup: true
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file: /home/travis/build/krate95/Calidad/SpaceInvaders/app/build/outputs/apk/release/spaceInvadersG6.apk
  on:
    repo: krate95/Calidad
    tags: true
    all_branches: true
env:
  global:
  - secure: iRGGlqEj6rAVftJ5SEfSVgcXh8RSNTWUTCPP4SwVO3CBFV49aSj7hwu4WSN2P835XnNrDzP7kW6a7sRmgZbRIgdYKPEHsd6z9mMpv7aezKEaRsGgv4kIYVXamRwggMQdNhFWMpptBETrDVdylTsqf8cbogCrmOQhO/hPnCkY4TS0W/XEkXP47+vrcQw9nc6FRknaMjtJSW5WmokuYMmyvqw0eN24EOSfyxpVmDdVwsVE8S5YukV7RfKMQlqqlhtORBpW5XrRc/vF10SYO7gHJhfBH5aAA6k0Sh1tkgfyoCSVcyCMFRUgkaAhnEVlfK28X/nQHKLsPyTciVUdQZME3V42vN6W9Ueo4Sjp1IHlF5/1/AN90vJpHfZVpYjn/uSnVNwZ9jorth9vxdWk46yf2h24/fORljMTXbhAKG7Eg+xIGEW+9/ioiKiUoXZ6pwb6lpncotbDTxnIZDeTs+sMtEQH7JXWPE4diSkcHDymBcvNFCYmlff+OtcU2UFZ9kKfeG7ExEVCJANuwgLakwvvDohcNby9InnBbUPmHD4W1LZzulSlST0u7z81l/uBO6BImk+o/ppAB0ZnQ0ZkosH9An/bqJK9FrssY4VuqRVwftwb+cJ7J6sNy/Rc4TlFO9XpubOPf79R9F6ydd0h9RYD9hWZzj3btCxCAKz1LIG9Z6k=
  - secure: oq2MiPA9y1uZckM9IccyXPCZKsCU3p3uzabFlhHA+4ulPDrcv9Q/WAnL2566XNw4QGYOW6A+FuOOVYBEcxOik4plS3XUcfzKaOSS0tSCiFsJDtaBEM+/MvqVBwSh/C+u8M6WOnNO1Du6TelF87MA+XDNnDLQZB4BOqJYcAQBaBv1jqLAjlTAjxYaKhamJ2yCLWInK8gI2RwQaZnSjNKAPf9sSCXDYACRRhwWAvZ1+JjIBS4Cb760cW+MvZEHOtX45Ux3Ogo8TcnM36h225bdqoqTy4YvMDgBIMNZEo5tJLkK7HjG4daaIYPfbm98tDwGnVXnTqWBufpYm5eaX2JwCENe8j09Ftnhi4dnI/Iy/h+koOFkplQYSD0KZvgxgs0TE22ltJ+70myfWjlhGdcmjzkBOIeVApPttc8eqUmWcE405hDw700ouzbuBUrfycGVLN2Qp4YbB488yCUGUbXdVbyBf5bZ/UqiOLYrTxWMNjc7TfgdhVH4pilKCyC6ENszQ+4CyKpSMYAmt4WBc60LFgx/qwg0peNbePLsxGHJxRrO0jIgBPTG3UATpmb2il6DrZ8ZvjYv5IVJ892hGRgndvsW9uBT7ZcceXOXDqwRY/Zt22Ez20L/pO9jF/qYw+yMEfHoDqyUQJIVWdNAh3jrYWdjNkOhKw53hVuA0vw0f8E=
