language: android
android:
  components:
  - android-28
  - build-tools-28.0.3
before_install:
- cd SpaceInvaders
- chmod +x gradlew
script:
- "./gradlew build"
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: "/home/travis/build/krate95/Calidad/SpaceInvaders/app/build/outputs/apk/"
  on:
    repo: krate95/Calidad
    tags: true
    all_branches: true
